format = """
[](#005f87)\
$os\
$username\
[](bg:#626262 fg:#005f87)\
$directory\
[](fg:#626262 bg:#eeeeee)\
$git_branch\
$git_commit\
$git_status\
$git_metrics\
$git_state\
[](fg:#eeeeee)\
$fill\
[](#eeeeee)\
$golang\
$dart\
$nodejs\
$rust\
[](fg:#eeeeee bg:#626262)\
$docker_context\
$jobs\
[](fg:#626262 bg:#005f87)\
$time\
[ ](fg:#005f87)
$python\
$character
"""

# Disable the blank line at the start of the prompt
#add_newline = true

[character]
success_symbol = '[➜](bold green) '
error_symbol = '[✗](bold red) '




# You can also replace your username with a neat symbol like  to save some space
[username]
show_always = true
style_user = "bg:#005f87 fg:15"
style_root = "bg:#005f87"
format = '[$user ]($style)'

# [os]
# format = "[($name)]($style)"
# style = "bg:#9A348E fg:15"
# name = "Pop"
# disabled = false

[directory]
style = "bg:#626262 fg:232"
format = "[ $path ]($style)"
truncation_length = 3
truncation_symbol = "…/"

# Here is how you can shorten some long paths by text replacement
# similar to mapped_locations in Oh My Posh:
[directory.substitutions]
"Documents" = " "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
"~" = ""
# Keep in mind that the order matters. For example:
# "Important Documents" = "  "
# will not be replaced, because "Documents" was already substituted before.
# So either put "Important Documents" before "Documents" or use the substituted version:
# "Important  " = "  "
[docker_context]
symbol = " "
style = "bg:#06969A"
format = '[ $symbol $context ]($style) $path'

[git_branch]
symbol = ""
style = "bg:#eeeeee fg:232"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:#eeeeee fg:232"
format = '[$all_status$ahead_behind ]($style)'
ahead = "⇡${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
behind = "⇣${count}"


[golang]
symbol = ""
style = "bg:#eeeeee fg:232"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:#eeeeee fg:232"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#eeeeee fg:232"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:#005f87"
format = '[ ♥ $time ]($style)'

[git_metrics]
added_style = "bg:#eeeeee fg:#0000FF"
deleted_style = "bg:#eeeeee fg:#FF0000"
format = "[+$added]($added_style)[ -$deleted]($deleted_style)"
disabled = false


[fill]
symbol = " "

[jobs]
format = "[]($style)"
style = "fg:#719cd6 bg:#06969A"

[python]
format = "[$symbol (venv) $version ]($style)"
style = "bg:bold"
pyenv_prefix = "pyenv"
detect_extensions = ['']
detect_folders = ['']
